In [1]:
import numpy as np 
import pandas as pd

In [2]:
import cv2

In [3]:
from tensorflow.keras.applications.vgg16 import VGG16, preprocess_input
from tensorflow.keras.models import Model
from sklearn.metrics.pairwise import cosine_similarity

In [5]:
base_model = VGG16(weights='imagenet')
model = Model(inputs=base_model.input, outputs=base_model.get_layer('fc1').output)

def extract_frames(video_path, frame_interval=1):
    cap = cv2.VideoCapture(video_path)
    frames = []
    count = 0

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break
        
        if count % frame_interval == 0:
            frame = cv2.resize(frame, (224, 224))  
            frames.append(frame)
        
        count += 1

    cap.release()
    return np.array(frames)

def extract_features(frames):
    features = []
    for frame in frames:
        frame = np.expand_dims(frame, axis=0) 
        frame = preprocess_input(frame)       
        feature = model.predict(frame)
        features.append(feature.flatten())    
    
    return np.array(features)

def compare_videos(video_path1, video_path2, frame_interval=1):
    frames1 = extract_frames(video_path1, frame_interval)
    frames2 = extract_frames(video_path2, frame_interval)
    
    if len(frames1) != len(frames2):
        min_frames = min(len(frames1), len(frames2))
        frames1 = frames1[:min_frames]
        frames2 = frames2[:min_frames]

    features1 = extract_features(frames1)
    features2 = extract_features(frames2)

    print("Feature Vectors for Video 1:")
    print(features1)

    print("\nFeature Vectors for Video 2:")
    print(features2)


    # Compute average cosine similarity
    similarities = []
    for feat1, feat2 in zip(features1, features2):
        sim = cosine_similarity([feat1], [feat2])[0][0]
        similarities.append(sim)
    
    average_similarity = np.mean(similarities)
    return average_similarity

# Example usage
video_path1 = r'C:\Users\Atharva Chepe\Desktop\similarity_videos\similarity1.mp4'
video_path2 = r'C:\Users\Atharva Chepe\Desktop\similarity_videos\testvid.mp4'

similarity_score = compare_videos(video_path1, video_path2, frame_interval=30)  
print(f"Similarity score between videos: {similarity_score}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 280ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 281ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 293ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 284ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 285ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 288ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 285ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 291ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 285ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 269ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 278ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 271ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 284ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 283ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 269ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 301ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 285ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 272ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 283ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 278ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 283ms/step
Feature Vectors for Video 1:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. 